services:
  desafio-globo:
    build: .
    container_name: desafio-globo-java
    ports:
      - "8081:8081"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    ports:
      - "6380:6379"
